#Makefile for dev folder

adev : adev.cxx toolbox.cxx Makefile
	g++ adev.cxx toolbox.cxx -std=c++17 -o ../bin/adev

bdev : bdev.cxx toolbox.cxx Makefile
	g++ bdev.cxx toolbox.cxx -std=c++17 -o ../bin/bdev
	
combi : combi.cpp Makefile
	g++ combi.cpp -std=c++17 -o ../bin/combi
